//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangSachHuynhTanPhatDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int maTaiKhoan { get; set; }
        public string tenDangNhap { get; set; }
        public string matKhau { get; set; }
        public int maNV { get; set; }
        public bool quyen { get; set; }
        public bool trangThai { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
